StartAt: "ClientForward"
States:
  ClientForward:
    Type: Map
    Iterator:
      StartAt: EmbedForward
      States:
        EmbedForward:
          Type: Task
          Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
          Parameters:
            QueueUrl.$: $.SqsUrl
            MessageBody:
              BatchSize.$: $.BatchSize
              BatchIndex.$: $.BatchIndex
              BatchCount.$: $.BatchCount
              Direction: Forward
              EpochIndex.$: $.EpochIndex
              EpochCount.$: $.EpochCount
              IsNextBatch.$: $.IsNextBatch
              IsNextVaBatch.$: $.IsNextVaBatch
              IsNextEpoch.$: $.IsNextEpoch
              Patience.$: $.Patience
              Phase: Training
              TaskName.$: $.TaskName
              TaskToken.$: $$.Task.Token
              ShuffledIndexPath.$: $.ShuffledIndexPath
              SparseEncoding.$: $.SparseEncoding
              SparseLambda.$: $.SparseLambda
              StateMachine.$: $$.StateMachine.Id
              TaskToken.$: $$.Task.Token
              VaBatchIndex.$: $.VaBatchIndex
              VaBatchCount.$: $.VaBatchCount
              VFLBucket.$: $.VFLBucket
          End: true
    Next: ServerTraining
  ServerTraining:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Parameters:
      FunctionName: ${ServerTrainingFunctionArn}
      Payload:
        InputItems.$: $
        Phase: Training
    Next: ClientBackward
  ClientBackward:
    Type: Map
    ItemsPath: $.Payload
    Iterator:
      StartAt: GradientBackward
      States:
        GradientBackward:
          Type: Task
          Resource: arn:aws:states:::sqs:sendMessage.waitForTaskToken
          Parameters:
            QueueUrl.$: $.SqsUrl
            MessageBody:
              BatchSize.$: $.BatchSize
              BatchIndex.$: $.BatchIndex
              BatchCount.$: $.BatchCount
              VaBatchIndex.$: $.VaBatchIndex
              VaBatchCount.$: $.VaBatchCount
              IsNextBatch.$: $.IsNextBatch
              IsNextVaBatch.$: $.IsNextVaBatch
              IsNextEpoch.$: $.IsNextEpoch
              EpochCount.$: $.EpochCount
              EpochIndex.$: $.EpochIndex
              TaskName.$: $.TaskName
              Patience.$: $.Patience
              ShuffledIndexPath.$: $.ShuffledIndexPath
              SparseEncoding.$: $.SparseEncoding
              SparseLambda.$: $.SparseLambda
              GradientFile.$: $.GradientFile
              TaskToken.$: $$.Task.Token
              StateMachine.$: $$.StateMachine.Id
              VFLBucket.$: $.VFLBucket
              Direction: Backward
              Phase: Training
          End: true
    Next: NextBatch?
  NextBatch?:
    Type: Choice
    Choices:
      - Variable: $[0].IsNextBatch
        BooleanEquals: true
        Next: PrepareNextBatch
    Default: End
  PrepareNextBatch:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Parameters:
      FunctionName: ${PrepareNextBatchFunctionArn}
      Payload:
        InputItems.$: $
    OutputPath: $.Payload
    Next: ClientForward
  End:
    Type: Pass
    End: true
